### ISSUE TITLE
Top level template section Globals is not valid on neovim

### ISSUE THREAD

**Issue by mbarneyjr** [LaurenceWarne/cfn-lsp-extra#3] opened 2023-03-24 03:19 UTC
I started using this with neovim recently and it doesn't seem to validate correctly with SAM templates. It complains about the Globals section, as well as other SAM-specific issues (like `ApiGatewayDefaultStage` not being found as a resource or parameter).

My nvim configuration can be found [here](https://github.com/mbarneyjr/.config-nvim), particularly [this file](https://github.com/mbarneyjr/.config-nvim/blob/main/lua/barney/lsp/custom/cfn-lsp-extra.lua).

I am still pretty new to neovim/LSPs in general so it's not super unlikely that I'm missing something.

Thanks for the really cool tool, autocomplete in neovim for cloudformation is awesome!

Neovim environment:

```bash
$ nvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by mbarney@T10171

Features: +acl +iconv +tui
```

**Comment by LaurenceWarne** [comment] 2023-03-24 12:16
Thanks for the report!  I can reproduce this, `cfn-lsp-extra` gets its lints from `cfn-lint` and I think what's happening is that we're not asking the runner to transform the SAM template to Cloudformation (funnily enough some features like resource type recognition work anyway :smile: ).

I've pushed a fix in https://github.com/LaurenceWarne/cfn-lsp-extra/commit/fbc8a906621bf7dfd2a52f3f8df1519f24c779a0, which works for me, would you be able to confirm this works for you?  To install from master, I think this should work:

```bash
pipx install git+https://github.com/laurencewarne/cfn-lsp-extra.git@$(git ls-remote git@github.com:laurencewarne/cfn-lsp-extra.git | head -1 | cut -f1) --force
```

Another way would be to clone, and then:
```
pipx install . --force
```

Then to be sure you've on the most recent commit `cfn-lsp-extra --version` should give `0.4.3`.

Thanks!

**Comment by mbarneyjr** [comment] 2023-03-24 13:54
That did the trick, thanks!

**Comment by LaurenceWarne** [comment] 2023-03-24 16:16
Great!  I've just cut off a new release with this change :slightly_smiling_face:

**Closed by LaurenceWarne** 2023-03-24 16:16 UTC
